version: "3"
services: 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports: 
      - 5432:5432
    volumes:
      - ./sql/query.sql:/docker-entrypoint-initdb.d/query.sql
